apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow--deployment                     # le nom du déploiement
spec:
  selector:
    matchLabels:
      app: mlflow--dashboard                    # ne pourront être utilisé que des ??? qui portent le nom "mlflow--dashboard"
  replicas: 2                                   # tells deployment to run 2 pods matching the name "mlflow--dashboard"
  template:
    metadata:
      labels:
        app: mlflow--dashboard
    spec:
      containers:
        - name: mlflow--server
          image: jedha/sample-mlflow-server
          envFrom:
            - secretRef:
                name: mlflow-env-variables      # see secrets.yaml