apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow--deployment
spec:
  selector:
    matchLabels:
      app: mlflow--dashboard
  replicas: 4                                # n pods matching the template name
  template:
    metadata:
      labels:
        app: mlflow--dashboard
    spec:
      containers:
        - name: mlflow--server
          image: jedha/sample-mlflow-server
          envFrom:
            - secretRef:
                name: mlflow-env-variables    # see secrets.yaml
   